name: pdf-compile
on:
    workflow_dispatch:
    pull_request:
    push:
jobs:
    pdf-compile:
        runs-on: ubuntu-latest
        container: aergus/latex:latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Install Python Pip
              run: apt install python3-pip && pip install Pygments
            - name: PDF compile
              run: latexmk -shell-escape thesis.tex
